### ISSUE TITLE
Route parameter without model binding

### ISSUE THREAD

**Issue by NandXor96** [robotsinside/laravel-breadcrumbs#1]
If you try to render a breadcrumb for a route with a parameter which is not bound to a model, you're getting the following error:

`get_class() expects parameter 1 to be object, string given`

in line 190 of Segment.php.

You may want to modify the label method in Segment.php to check if $this->model() is an object. 
If it's not, you could return $this->segmentTitleCase()

**Comment by robfrancken** [comment]
Nice catch, thanks for pointing that out. I'll have a look at it this weekend. Also happy to accept a PR.
